// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3WB9pusZR_vzYGNMMCK4Xz-s8ZmC6js',
    appId: '1:189067051352:web:3f0fff276fa96a3e4ca52d',
    messagingSenderId: '189067051352',
    projectId: 'back-685c7',
    authDomain: 'back-685c7.firebaseapp.com',
    storageBucket: 'back-685c7.appspot.com',
    measurementId: 'G-TNKEZPJM9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWzRiXFKS1E3k14yJBi6JPFjn6OIqAfo4',
    appId: '1:189067051352:android:36c913c973db81024ca52d',
    messagingSenderId: '189067051352',
    projectId: 'back-685c7',
    storageBucket: 'back-685c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-CxSpHTLtXIuw8LKRqaLAQBpoqqls8g',
    appId: '1:189067051352:ios:b8e59e2a4d4d284c4ca52d',
    messagingSenderId: '189067051352',
    projectId: 'back-685c7',
    storageBucket: 'back-685c7.appspot.com',
    iosBundleId: 'com.example.totalx1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ-CxSpHTLtXIuw8LKRqaLAQBpoqqls8g',
    appId: '1:189067051352:ios:b8e59e2a4d4d284c4ca52d',
    messagingSenderId: '189067051352',
    projectId: 'back-685c7',
    storageBucket: 'back-685c7.appspot.com',
    iosBundleId: 'com.example.totalx1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz3WB9pusZR_vzYGNMMCK4Xz-s8ZmC6js',
    appId: '1:189067051352:web:28f79d3ce815fa064ca52d',
    messagingSenderId: '189067051352',
    projectId: 'back-685c7',
    authDomain: 'back-685c7.firebaseapp.com',
    storageBucket: 'back-685c7.appspot.com',
    measurementId: 'G-D9ZJ7ZQ7TF',
  );

}